package by.it.academy.newsportal.controller;

public enum CommandName {
	REGISTRATION , AUTHORIZATION,REGISTRATION_NEW_USER,UNKNOWN_COMMAND,
	GO_TO_MAIN_PAIGE, SIGN_IN, GO_TO_AUTORIZATION_USER_PAGE,CHANGE_LOCALE,LOGOUT,
}